### ISSUE TITLE
aciTree context menu documentation appears to be missing

### ISSUE THREAD

**Issue by gawpertron** [dragosu/jquery-aciTree#5]
Are there any examples for the context menu API?

i.e aciTree-context-menu.html is missing link in aciTree.html

**Comment by dragosu** [comment]
You can see a small demo here: http://acoderinsights.ro/demo/aciTree-context-menu.html;
but there is no aciTree API for a context menu, it's just a demo using http://medialize.github.io/jQuery-contextMenu/ to implement a context menu for aciTree (with some functions using the API).
You can use any other context menu library ...
